# coding=utf-8
"""
QMT 策略组装脚本
1. 读取 core/ + adapters/ 的 Python 文件
2. 内联合并为一个文件
3. 自动 UTF-8 -> GBK 编码转换
4. 输出 strategy_main.py

用法: python scripts/build_strategy.py
"""
import os
import re
import ast
import builtins
import glob
import argparse
from datetime import datetime

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# QMT 生命周期模板
LIFECYCLE_TEMPLATE = """
# ====== QMT Lifecycle ======

def init(C):
    C.runner = StrategyRunner()
    C.runner.init(C)

def after_init(C):
    pass

def handlebar(C):
    runner = getattr(C, 'runner', None)
    if runner is not None:
        try:
            runner.handlebar(C)
        except KeyboardInterrupt:
            print("  [策略] 已手动停止，正在退出...")
            raise

def exit(C):
    runner = getattr(C, 'runner', None)
    if runner is not None:
        runner.exit(C)
"""


def strip_coding_header(source):
    """移除 # coding=xxx 行"""
    lines = source.split('\n')
    if lines and re.match(r'^#\s*coding[=:]\s*\S+', lines[0]):
        lines = lines[1:]
    if lines and re.match(r'^#\s*coding[=:]\s*\S+', lines[0]):
        lines = lines[1:]
    return '\n'.join(lines)


def is_intra_project_import(line):
    """检查是否属于项目内部 import（需要内联化）"""
    stripped = line.strip()
    if stripped.startswith('import core.') or stripped.startswith('from core.'):
        return True
    if stripped.startswith('import adapters.') or stripped.startswith('from adapters.'):
        return True
    return False


def strip_intra_imports(source):
    """移除项目内部 import 语句"""
    lines = source.split('\n')
    filtered = []
    for line in lines:
        stripped = line.strip()
        if is_intra_project_import(stripped):
            # 跳过整行及可能的续行
            if stripped.endswith('\\'):
                continue
            continue
        # 过滤多行导入中的内部引用
        filtered.append(line)
    return '\n'.join(filtered)


def read_source(filepath):
    """读取源文件，处理编码和 imports"""
    full_path = os.path.join(BASE_DIR, filepath)
    with open(full_path, 'r', encoding='utf-8') as f:
        source = f.read()
    source = strip_coding_header(source)
    source = strip_intra_imports(source)
    return source


def build_strategy_main(source_files):
    """组装 strategy_main.py"""
    parts = []
    parts.append('# coding=gbk')
    now_str = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    parts.append('# 生成时间: %s' % now_str)
    parts.append('"""QMT Strategy - Auto-generated by build_strategy.py"""')
    parts.append('')

    for filepath in source_files:
        source = read_source(filepath)
        if not source.strip():
            continue
        # 去掉文件末尾的空白
        source = source.rstrip()
        # 加入文件标记
        parts.append('')
        parts.append('# ====== %s ======' % filepath)
        parts.append(source)

    # 追加生命周期
    parts.append(LIFECYCLE_TEMPLATE)
    parts.append('')

    merged = '\n'.join(parts)
    return merged


def _force_gbk(content, output_path=None):
    """强制转GBK，不可转码字符报错中断"""
    try:
        gbk_bytes = content.encode('gbk')
        return gbk_bytes
    except UnicodeEncodeError as e:
        offending_line = content[:e.start].count('\n') + 1
        offending_char = e.object[e.start:e.end]
        path_display = output_path or '<unknown>'
        raise RuntimeError(
            "\n"
            "============================================\n"
            " GBK编码失败！\n"
            "============================================\n"
            " 文件: %s\n"
            " 第 %d 行有不可转码字符: %r\n"
            " 原因: %s\n"
            "============================================\n"
            " 提示: 替换为GBK兼容符号（如 √×▲▼○● 等）\n"
            "============================================\n"
            % (path_display, offending_line, offending_char, e.reason)
        )


# QMT 运行时提供的内置函数（exec 环境特有）
QMT_BUILTINS = {
    'passorder', 'get_trade_detail_data', 'get_market_data_ex',
    'get_current_time', 'get_full_topic', 'get_local_topic',
    'get_option', 'get_stock_list_in_sector', 'get_sector_list',
    'get_industry_list', 'get_stock_list_in_industry',
    'get_stock_basic_info', 'get_market_data', '__file__',
    'ContextInfo', 'GLOBAL_ACCOUNT',
}


def _defined_names_in_scope(func_node):
    """收集某个函数作用域内定义的名字（参数 + Store + import + except + comprehension + 嵌套函数名）。"""
    defined = set()
    defined.add(func_node.name)
    defined.update(a.arg for a in func_node.args.args)

    for node in ast.walk(func_node):
        if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Store):
            defined.add(node.id)
        elif isinstance(node, ast.ExceptHandler) and node.name:
            defined.add(node.name)
        elif isinstance(node, ast.Import):
            for alias in node.names:
                defined.add(alias.asname or alias.name.split('.')[0])
        elif isinstance(node, ast.ImportFrom):
            for alias in node.names:
                defined.add(alias.asname or alias.name)
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node is not func_node:
            defined.add(node.name)
    return defined


def _walk_and_check(nodes, defined, module_vars, builtins_set, warnings=None):
    """递归遍历 AST 节点，检查 Name.Load。遇到嵌套 FunctionDef 则递归（传入 parent scope）。"""
    if warnings is None:
        warnings = []
    for node in nodes:
        _check_node(node, defined, module_vars, builtins_set, warnings)
    return warnings


def _check_node(node, defined, module_vars, builtins_set, warnings):
    """检查单个 AST 节点，递归遍历子节点。"""
    if isinstance(node, ast.FunctionDef):
        # 嵌套函数：把当前作用域传给它的递归检查，但不检查它的主体作为当前作用域
        ndef = _defined_names_in_scope(node) | defined
        _walk_and_check(node.body, ndef, module_vars, builtins_set, warnings)
        return

    if isinstance(node, ast.Lambda):
        # Lambda 表达式：参数在自己作用域内
        ldef = set(defined)
        ldef.update(a.arg for a in node.args.args)
        _walk_and_check([node.body], ldef, module_vars, builtins_set, warnings)
        return

    if isinstance(node, (ast.ListComp, ast.SetComp, ast.DictComp, ast.GeneratorExp)):
        # 推导式：generator target 在推导式作用域内
        cdef = set(defined)
        for gen in node.generators:
            if isinstance(gen.target, ast.Name):
                cdef.add(gen.target.id)
            elif isinstance(gen.target, ast.Tuple):
                for elt in gen.target.elts:
                    if isinstance(elt, ast.Name):
                        cdef.add(elt.id)
        _walk_and_check(node.generators, cdef, module_vars, builtins_set, warnings)
        if isinstance(node, ast.DictComp):
            _walk_and_check([node.key, node.value], cdef, module_vars, builtins_set, warnings)
        else:
            _walk_and_check([node.elt], cdef, module_vars, builtins_set, warnings)
        return

    if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Load):
        nid = node.id
        if nid not in defined and nid not in module_vars and nid not in builtins_set:
            warnings.append((node.lineno, nid))
        return

    # 递归到子节点
    for child in ast.iter_child_nodes(node):
        _check_node(child, defined, module_vars, builtins_set, warnings)


def _module_level_names(tree):
    """收集模块级定义的名字：import、赋值、函数、类。"""
    names = set()
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            names.add(node.name)
        elif isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name):
                    names.add(t.id)
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            names.add(node.target.id)
        elif isinstance(node, ast.Import):
            for alias in node.names:
                names.add(alias.asname or alias.name.split('.')[0])
        elif isinstance(node, ast.ImportFrom):
            for alias in node.names:
                names.add(alias.asname or alias.name.split('.')[0])
    return names


def validate_strategy(source, output_path):
    """对合并后的产物做静态校验：语法 + 未定义名字扫描。"""
    # 1) compile() 语法校验
    try:
        compile(source, output_path, 'exec')
    except SyntaxError as e:
        raise RuntimeError("  语法错误: %s" % e)

    # 2) AST 扫描未定义的名字
    try:
        tree = ast.parse(source, filename=output_path)
    except SyntaxError as e:
        raise RuntimeError("  AST解析错误: %s" % e)

    module_vars = _module_level_names(tree)
    builtins_set = set(dir(builtins)) | QMT_BUILTINS

    all_warnings = []
    for node in tree.body:
        if isinstance(node, ast.FunctionDef):
            defined = _defined_names_in_scope(node) | module_vars | builtins_set
            _walk_and_check(node.body, defined, module_vars, builtins_set, all_warnings)

    # 去重
    seen = set()
    unique = []
    for lineno, name in all_warnings:
        key = (lineno, name)
        if key not in seen:
            seen.add(key)
            unique.append((lineno, name))

    if unique:
        # GBK 安全输出
        print("\n  [WARNING] 以下名字在函数内被引用但未在本模块找到定义:")
        for lineno, name in sorted(unique):
            print("    行 %-5d %s" % (lineno, name))
        print("  说明: 可能是 QMT 运行时内置函数或外部依赖，请人工确认")

    return True


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--dev', action='store_true', help='构建开发版(含MOCK)')
    parser.add_argument('--allday', action='store_true', help='构建全天调试版(DEBUG_MODE硬编码True,不含MOCK)')
    parser.add_argument('--test', action='store_true', help='构建后自动跑miniQMT测试(需本地QMT环境)')
    args = parser.parse_args()

    # 需要合并的源文件（按依赖顺序排列）
    SOURCE_FILES = [
        'core/utils.py',
        'core/scoring/dimension6plus2.py',  # 6+2 scorer — before signal_main_rise
        'core/signal_main_rise.py',
        'core/scoring/switch_scorer.py',    # 8D<->6+2 switch wrapper
        'core/risk_manager.py',
        'core/position_sizer.py',
        'adapters/exit_adapters/base.py',   # 策略侧止盈适配层基类
        'adapters/exit_adapters/trend_62.py',  # 趋势型6+2止盈适配器
        'adapters/exit_adapters/__init__.py',  # 策略适配器注册入口
    ]

    # 仅在 --dev 模式下加入 MOCK
    if args.dev:
        SOURCE_FILES.append('adapters/context_mock.py')

    SOURCE_FILES.append('adapters/qmt_wrapper.py')
    SOURCE_FILES.append('adapters/export_logger.py')  # 导出/日志函数（拆分自 qmt_wrapper）

    suffix = '_dev' if args.dev else '_main'
    if args.allday:
        output_name = 'strategy_allday.py'
        version_label = '全天调试版'
        mock_label = '不含MOCK'
    else:
        output_name = 'strategy%s.py' % suffix
        version_label = '开发版' if args.dev else '生产版'
        mock_label = '含MOCK' if args.dev else '不含MOCK'
    OUTPUT_PATH = os.path.join(BASE_DIR, 'deploy', output_name)

    print('Building %s ...' % output_name)
    content = build_strategy_main(SOURCE_FILES)

    # --allday: 硬编码 DEBUG_MODE = True（覆盖yaml配置，支持两个文件共存）
    if args.allday:
        old_line = "DEBUG_MODE = _debug_config.get('enabled', False)"
        new_line = "DEBUG_MODE = True"
        if old_line in content:
            content = content.replace(old_line, new_line)
            print('  [allday] 硬编码 DEBUG_MODE = True')
        else:
            raise RuntimeError(
                "未找到 '%s' 行，无法硬编码 DEBUG_MODE。请检查 adapters/qmt_wrapper.py 中的 DEBUG_MODE 定义。"
                % old_line
            )

    # --dev: 硬编码 TEST_MODE = True（开发版需全天可触发交易循环）
    if args.dev:
        old_line = "TEST_MODE = False"
        new_line = "TEST_MODE = True"
        if old_line in content:
            content = content.replace(old_line, new_line)
            print('  [dev] 硬编码 TEST_MODE = True')
        else:
            raise RuntimeError(
                "未找到 '%s' 行，无法硬编码 TEST_MODE。请检查 adapters/qmt_wrapper.py 中的 TEST_MODE 定义。"
                % old_line
            )

    gbk_bytes = _force_gbk(content, OUTPUT_PATH)

    with open(OUTPUT_PATH, 'wb') as f:
        f.write(gbk_bytes)

    print('OK: %s (%s, %s)' % (output_name, version_label, mock_label))
    print('Size: %d bytes' % os.path.getsize(OUTPUT_PATH))

    # 验证文件头
    with open(OUTPUT_PATH, 'r', encoding='gbk') as f:
        first_line = f.readline().strip()
    print('First line: %s' % first_line)
    assert first_line == '# coding=gbk', '文件头不是 # coding=gbk'

    # 验证编码
    try:
        with open(OUTPUT_PATH, 'r', encoding='gbk') as f:
            content = f.read()
        print('Encoding: GBK (verified by reading with gbk)')
    except UnicodeDecodeError:
        print('ERROR: 文件不是有效的GBK编码')
        raise

    # 编译期校验
    print('Validating... ', end='', flush=True)
    try:
        valid = validate_strategy(content, OUTPUT_PATH)
        print('OK' if valid else 'Warnings')
    except RuntimeError as e:
        print('FAILED')
        print(str(e))
        # 删除无效产物，避免部署到 QMT
        if os.path.exists(OUTPUT_PATH):
            os.remove(OUTPUT_PATH)
            print('  已删除无效产物: %s' % OUTPUT_PATH)
        raise

    print('Done.')

    # 可选: 构建后自动跑 miniQMT 测试
    if args.test:
        _run_miniqmt_tests()


if __name__ == '__main__':
    main()


def _run_miniqmt_tests():
    """构建后自动跑 miniQMT 测试（需本地QMT环境）"""
    QMT_PYTHON = r'E:\国金QMT交易端模拟\bin.x64\python.exe'
    TEST_SCRIPTS = [
        r'D:\QMT_STRATEGIES\scripts\qmt_test_01_data_path.py',
        r'D:\QMT_STRATEGIES\scripts\qmt_test_02_strategy_components.py',
        r'D:\QMT_STRATEGIES\scripts\qmt_test_03_full_flow.py',
    ]

    if not os.path.exists(QMT_PYTHON):
        print('\n  [QMT测试] 跳过: 本地QMT Python未安装 (%s)' % QMT_PYTHON)
        return

    import subprocess
    print('\n' + '=' * 50)
    print('  运行 miniQMT 测试...')
    print('=' * 50)

    all_pass = True
    for script in TEST_SCRIPTS:
        if not os.path.exists(script):
            print('\n  [QMT测试] 跳过: 测试脚本不存在 %s' % script)
            continue
        print('\n  --- %s ---' % os.path.basename(script))
        try:
            result = subprocess.run(
                [QMT_PYTHON, script],
                capture_output=True, timeout=120
            )
            # QMT Python 输出 GBK，用二进制读后转 UTF-8
            stdout = result.stdout.decode('utf-8', errors='replace')
            # 提取 JSON 结果
            import json
            if '---JSON-START---' in stdout:
                json_str = stdout.split('---JSON-START---')[1].split('---JSON-END---')[0].strip()
                data = json.loads(json_str)
                status = data.get('status', 'FAIL')
                summary = data.get('summary', '')
                if status == 'PASS':
                    print('  [PASS] %s' % summary)
                else:
                    print('  [FAIL] %s' % summary)
                    all_pass = False
                for d in data.get('details', []):
                    mark = 'PASS' if d['status'] == 'PASS' else 'FAIL'
                    print('    [%s] %s: %s' % (mark, d['name'], d['detail']))
            else:
                print(stdout[-500:] if len(stdout) > 500 else stdout)
                if result.returncode != 0:
                    all_pass = False
        except subprocess.TimeoutExpired:
            print('  [FAIL] 超时')
            all_pass = False
        except Exception as e:
            print('  [FAIL] 异常: %s' % e)
            all_pass = False

    print('\n' + '=' * 50)
    if all_pass:
        print('  miniQMT 测试: ALL PASS')
    else:
        print('  miniQMT 测试: 有失败项，请检查上方日志')
    print('=' * 50)
