# -*- coding: utf-8 -*-
"""Rebuild risk_only_strategy.py from known code patterns."""
import os, sys

def w(s):
    out.append(s)

out = []

# === Header ===
w('# -*- coding: gbk -*-')
w('"""风控专用策略 - 只做卖出/减仓/预警/确认/清仓/移动止盈版本，不参与买入执行。"""')
w('')
w('import os')
w('import json')
w('import math')
w('import numpy as np')
w('import pandas as pd')
w('from datetime import datetime')
w('from enum import Enum')
w('')

# === Utility functions ===
w('def ema(series, n):')
w('    return series.ewm(span=n, adjust=False).mean()')
w('')
w('def ma(series, n):')
w('    return series.rolling(n).mean()')
w('')
w('def safe_last(series):')
w('    if series is None or len(series) == 0: return 0.0')
w('    val = series.iloc[-1]')
w('    return float(val) if not pd.isna(val) else 0.0')
w('')
w('def calc_macd(close):')
w('    diff = ema(close, 12) - ema(close, 26)')
w('    dea = ema(diff, 9)')
w('    macd = 2 * (diff - dea)')
w('    return diff, dea, macd')
w('')
w('def calc_atr(close, high, low, n=14):')
w('    prev_close = close.shift(1)')
w('    tr1 = high - low')
w('    tr2 = (high - prev_close).abs()')
w('    tr3 = (low - prev_close).abs()')
w('    tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)')
w('    atr = tr.ewm(span=n, adjust=False).mean()')
w('    return atr')
w('')
w('def calc_angle_simple(ma_series):')
w('    if len(ma_series) < 3: return None')
w('    try:')
w('        prev = float(ma_series.iloc[-2])')
w('        curr = float(ma_series.iloc[-1])')
w('        if prev <= 0: return None')
w('        rad = np.arctan((curr - prev) / prev * 100)')
w('        return float(rad * 180 / np.pi)')
w('    except Exception: return None')
w('')
w('def calc_kdj(close, high, low, n=9, m1=3, m2=3):')
w('    L = low.rolling(n).min()')
w('    H = high.rolling(n).max()')
w('    rsv = (close - L) / (H - L) * 100')
w('    rsv = rsv.fillna(50)')
w('    k = rsv.ewm(alpha=1.0/m1, adjust=False).mean()')
w('    d = k.ewm(alpha=1.0/m2, adjust=False).mean()')
w('    j = 3 * k - 2 * d')
w('    return k.fillna(50), d.fillna(50), j.fillna(50)')
w('')
w('def detect_long_upper_shadow(high, close, open_, sr=0.5):')
w('    body_top = pd.concat([close, open_], axis=1).max(axis=1)')
w('    upper = high - body_top')
w('    total = high - pd.concat([close, open_], axis=1).min(axis=1)')
w('    total = total.replace(0, np.nan)')
w('    return (upper / total).fillna(0) >= sr')
w('')
w('def detect_volume_price_divergence(close, volume, lb=5, th=0.70):')
w('    if len(close) < 2: return False, 0.0')
w('    if close.iloc[-1] < close.iloc[-lb:].max(): return False, 0.0')
w('    r = volume.iloc[-1] / volume.iloc[-2] if volume.iloc[-2] > 0 else 1')
w('    return (True, float(r)) if r < th else (False, float(r))')
w('')

# === Constants ===
w('BOTTOM_LINE_LOSS_PCT = -0.05')
w('BOTTOM_LINE_DAILY_DROP_PCT = -0.07')
w('WARNING_REDUCE_PCT = 0.30')
w('WARNING_ADD_REDUCE_PCT = 0.20')
w('VOLUME_RATIO_THRESHOLD = 1.5')
w('VOLUME_DIVERGE_THRESHOLD = 0.70')
w('MACD_SHORTEN_DAYS = 3')
w('MA5_SLOPE_FLAT_DEG = 15')
w('CONFIRM_REDUCE_PCT = 0.50')
w('CLEAR_MA20_DAYS = 3')
w('REBOUND_WINDOW_DAYS = 3')
w('TRAILING_BREAK_MA5_INTERVAL = 0.10')
w('TRAILING_DRAWDOWN_LO = 0.06')
w('TRAILING_DRAWDOWN_MID = 0.08')
w('TRAILING_DRAWDOWN_HI = 0.10')
w('CHANDELIER_ATR_MULTIPLE = 3')
w('NO_REENTRY_DAYS = 20')
w('CHANDELIER_MIN_LOOKBACK = 20')
w('KDJ_N = 9')
w('KDJ_M1 = 3')
w('KDJ_M2 = 3')
w('VOL_MA_PERIOD = 5')
w('CHANDELIER_LOOKBACK = 20')
w('')

# === Classes ===
w('class Action(Enum):')
w('    HOLD = "持有"')
w('    REDUCE = "减仓"')
w('    CLEAR = "清仓"')
w('')
w('class SellDecision:')
w('    def __init__(self, action=Action.HOLD, code="", sell_pct=0.0, reason="",')
w('                 triggered_layer="", triggered_signals=None):')
w('        self.action = action')
w('        self.code = code')
w('        self.sell_pct = sell_pct')
w('        self.reason = reason')
w('        self.triggered_layer = triggered_layer')
w('        self.triggered_signals = triggered_signals if triggered_signals is not None else []')
w('')
w('    @staticmethod')
w('    def hold():')
w('        return SellDecision()')
w('')
w('    @staticmethod')
w('    def reduce(code, pct, reason, layer, signals=None):')
w('        return SellDecision(Action.REDUCE, code, pct, reason, layer, signals or [])')
w('')
w('    @staticmethod')
w('    def clear(code, reason, layer, signals=None):')
w('        return SellDecision(Action.CLEAR, code, 1.0, reason, layer, signals or [])')
w('')
w('class SellPositionState:')
w('    def __init__(self, code="", cost_price=0.0, current_shares=0, original_shares=0,')
w('                 highest_price=0.0, entry_date="",')
w('                 warning_reduced=False, warning_trigger_date="", warning_reason="",')
w('                 b1_needs_nextday_check=False, b1_trigger_date="", b1_additional_reduced=False,')
w('                 confirm_reduced=False, confirm_trigger_date="", confirm_reason="",')
w('                 cleared=False, cleared_date="", rebound_restored=False, reduction_volume=0):')
w('        self.code = code')
w('        self.cost_price = cost_price')
w('        self.current_shares = current_shares')
w('        self.original_shares = original_shares')
w('        self.highest_price = highest_price')
w('        self.entry_date = entry_date')
w('        self.warning_reduced = warning_reduced')
w('        self.warning_trigger_date = warning_trigger_date')
w('        self.warning_reason = warning_reason')
w('        self.b1_needs_nextday_check = b1_needs_nextday_check')
w('        self.b1_trigger_date = b1_trigger_date')
w('        self.b1_additional_reduced = b1_additional_reduced')
w('        self.confirm_reduced = confirm_reduced')
w('        self.confirm_trigger_date = confirm_trigger_date')
w('        self.confirm_reason = confirm_reason')
w('        self.cleared = cleared')
w('        self.cleared_date = cleared_date')
w('        self.rebound_restored = rebound_restored')
w('        self.reduction_volume = reduction_volume')
w('')

# === get_trade_state_reason ===
w('def get_trade_state_reason(state):')
w('    if state is None: return "无状态"')
w('    if state.cleared: return "已清仓(%s)" % (state.cleared_date or "?")')
w('    if state.confirm_reduced: return "确认已减(%s)" % (state.confirm_reason or "?")')
w('    if state.warning_reduced: return "预警已减(%s)" % (state.warning_reason or "?")')
w('    if state.b1_needs_nextday_check: return "B1触过预警(待次日确认)"')
w('    return "正常持有"')
w('')

# === SellStrategyEngine ===
w('class SellStrategyEngine:')
w('    def __init__(self, strategy_name, account_id,')
w('                 state_file, is_intraday=True,')
w('                 hard_stop_loss=BOTTOM_LINE_LOSS_PCT):')
w('        self.strategy_name = strategy_name')
w('        self.account_id = account_id')
w('        self.state_file = state_file')
w('        self.is_intraday = is_intraday')
w('        self.hard_stop_loss = hard_stop_loss')
w('        self._states = {}')
w('')
w('    def load_state(self):')
w('        self._states = {}')
w('        if not os.path.exists(self.state_file): return')
w('        try:')
w('            with open(self.state_file, "r", encoding="utf-8") as f:')
w('                raw = json.load(f)')
w('            for code, data in raw.items():')
w('                ok = {k:v for k,v in data.items() if k in SellPositionState.__init__.__code__.co_varnames}')
w('                self._states[code] = SellPositionState(**ok)')
w('        except Exception: pass')
w('')
w('    def save_state(self):')
w('        if not self._states: return')
w('        try:')
w('            d = os.path.dirname(self.state_file)')
w('            if d: os.makedirs(d, exist_ok=True)')
w('            with open(self.state_file, "w", encoding="utf-8") as f:')
w('                json.dump({c:s.__dict__ for c,s in self._states.items()}, f, ensure_ascii=False, indent=2)')
w('        except Exception: pass')
w('')
w('    def _get_state(self, code): return self._states.get(code)')
w('')
w('    def _save_state(self, code, state):')
w('        self._states[code] = state; self.save_state()')
w('')
w('    def is_reentry_allowed(self, code, today, df=None):')
w('        st = self._states.get(code)')
w('        if not st or not st.cleared or not st.cleared_date: return True')
w('        c = datetime.strptime(st.cleared_date, "%Y%m%d")')
w('        t = datetime.strptime(today, "%Y%m%d")')
w('        if df is not None:')
w('            dts = pd.to_datetime(df.index)')
w('            ok = len(dts[(dts > pd.Timestamp(st.cleared_date)) & (dts <= pd.Timestamp(today))]) >= NO_REENTRY_DAYS')
w('        else:')
w('            ok = (t - c).days >= NO_REENTRY_DAYS + 8')
w('        if ok: self._states.pop(code, None); self.save_state()')
w('        return ok')
w('')
w('    def confirm_clear(self, code, today):')
w('        st = self._get_state(code)')
w('        if st: st.cleared = True; st.cleared_date = today; st.current_shares = 0; self._save_state(code, st)')
w('')
w('    def check_rebound(self, code, df, state, today):')
w('        if not state.warning_reduced or state.rebound_restored: return False, 0, ""')
w('        if not state.warning_trigger_date: return False, 0, ""')
w('        d = (datetime.strptime(today, "%Y%m%d") - datetime.strptime(state.warning_trigger_date, "%Y%m%d")).days')
w('        if d < 1 or d > REBOUND_WINDOW_DAYS:')
w('            if d > REBOUND_WINDOW_DAYS: state.rebound_restored = True')
w('            return False, 0, ""')
w('        cl = df["close"].astype(float); op = df["open"].astype(float); hi = df["high"].astype(float)')
w('        p = float(cl.iloc[-1])')
w('        if p <= float(cl.rolling(5).mean().iloc[-1]): return False, 0, ""')
w('        if p <= float(op.iloc[-1]): return False, 0, ""')
w('        if len(cl) >= 2 and p <= float(hi.iloc[-2]): return False, 0, ""')
w('        return (True, state.reduction_volume, "反弹修复") if state.reduction_volume > 0 else (False, 0, "")')
w('')
w('    def apply_rebound_state(self, code, state):')
w('        state.rebound_restored = True; state.warning_reduced = False')
w('        state.warning_trigger_date = ""; state.warning_reason = ""')
w('        state.b1_needs_nextday_check = False; state.b1_trigger_date = ""')
w('        state.b1_additional_reduced = False; state.confirm_reduced = False')
w('        state.confirm_trigger_date = ""; state.confirm_reason = ""')
w('        state.cleared = False; state.cleared_date = ""; state.reduction_volume = 0')
w('        self._save_state(code, state)')
w('')
w('    def evaluate(self, today, holdings_dict, all_data, positions_data=None):')
w('        if positions_data is None: positions_data = {}')
w('        decisions = []')
w('        if not holdings_dict: return decisions')
w('        for code in list(holdings_dict.keys()):')
w('            df = all_data.get(code)')
w('            if df is None or len(df) < 30: continue')
w('            state = self._get_state(code) or SellPositionState(code=code)')
w('            close = df["close"].astype(float)')
w('            curr = float(close.iloc[-1])')
w('            pos = positions_data.get(code, {})')
w('            if state.cleared and pos.get("volume", 0) > 0 and self.is_reentry_allowed(code, today, df):')
w('                state = SellPositionState(code=code)')
w('            cost = pos.get("cost", 0)')
w('            if cost > 0: state.cost_price = cost')
w('            state.current_shares = pos.get("can_use", 0)')
w('            state.highest_price = max(holdings_dict.get(code, curr), curr)')
w('            decision = self._evaluate_position(code, df, state, today)')
w('            if decision.action != Action.HOLD:')
w('                n = int(state.current_shares * decision.sell_pct)')
w('                if n >= 100:')
w('                    n = (n // 100) * 100')
w('                    if decision.action == Action.REDUCE:')
w('                        if decision.triggered_layer == "预警层":')
w('                            state.warning_reduced = True; state.warning_trigger_date = today')
w('                            state.warning_reason = decision.reason; state.reduction_volume += n')
w('                        elif decision.triggered_layer == "warning_add":')
w('                            state.b1_additional_reduced = True; state.b1_needs_nextday_check = False')
w('                            state.reduction_volume += n')
w('                        elif decision.triggered_layer == "确认层":')
w('                            state.confirm_reduced = True; state.confirm_trigger_date = today')
w('                            state.confirm_reason = decision.reason')
w('                self._save_state(code, state)')
w('                decisions.append((code, decision, n))')
w('        return decisions')
w('')
w('    def _evaluate_position(self, code, df, state, today):')
w('        close = df["close"].astype(float); high = df["high"].astype(float)')
w('        low = df["low"].astype(float); open_ = df["open"].astype(float)')
w('        vol = df["volume"].astype(float)')
w('        d = self._check_bottom_line(close, high, code, state, today)')
w('        if d.action != Action.HOLD: return d')
w('        if state.cleared: return SellDecision.hold()')
w('        d = self._check_clear_level(close, high, low, vol, df, state, today)')
w('        if d.action != Action.HOLD: return d')
w('        if not state.warning_reduced:')
w('            sigs = []')
w('            b1, r1 = self._signal_explosive_volume(close, high, open_, vol)')
w('            if b1: sigs.append(r1); state.b1_needs_nextday_check = True; state.b1_trigger_date = today')
w('            if self._signal_volume_divergence(close, vol): sigs.append("B2:量价背离")')
w('            if self._signal_macd_shortening(close): sigs.append("C2:MACD绿柱缩短")')
w('            if self._signal_kdj_death(close, high, low): sigs.append("KDJ死叉+MA5走平")')
w('            if sigs:')
w('                state.warning_reduced = True; state.warning_trigger_date = today')
w('                r = " | ".join(sigs); state.warning_reason = r')
w('                self._save_state(code, state)')
w('                return SellDecision.reduce(code, WARNING_REDUCE_PCT, r, "预警层", sigs)')
w('        if state.warning_reduced and not state.confirm_reduced:')
w('            if state.b1_needs_nextday_check and not state.b1_additional_reduced:')
w('                bd = self._check_b1_nextday_additional(close, open_, code, state, today)')
w('                if bd.action != Action.HOLD: return bd')
w('            cd = self._check_confirm_level(close, high, low, open_, vol, df, state, today)')
w('            if cd.action != Action.HOLD: return cd')
w('        return SellDecision.hold()')
w('')

# === Bottom line ===
w('    def _check_bottom_line(self, close, high, code, state, today):')
w('        if len(close) < 2: return SellDecision.hold()')
w('        p = float(close.iloc[-1]); sigs = []')
w('        if state.cost_price > 0:')
w('            l = (p - state.cost_price) / state.cost_price')
w('            if l <= BOTTOM_LINE_LOSS_PCT:')
w('                sigs.append("累计亏损%.1f%%" % (l*100))')
w('                return SellDecision.clear(code, "硬止损:累计亏损%.1f%%" % (l*100), "底线层", sigs)')
w('        pc = float(close.iloc[-2])')
w('        if pc > 0:')
w('            dd = (p - pc) / pc')
w('            if dd <= BOTTOM_LINE_DAILY_DROP_PCT:')
w('                sigs.append("当日跌停%.1f%%" % (dd*100))')
w('                return SellDecision.clear(code, "硬止损:当日跌停%.1f%%" % (dd*100), "底线层", sigs)')
w('        return SellDecision.hold()')
w('')

# === B1 next day ===
w('    def _check_b1_nextday_additional(self, close, open_, code, state, today):')
w('        if not state.b1_trigger_date or today <= state.b1_trigger_date: return SellDecision.hold()')
w('        if self._signal_b1_nextday_unrecovered(close, open_, state):')
w('            return SellDecision.reduce(code, WARNING_ADD_REDUCE_PCT, "B1次日未修复", "warning_add", ["B1次日未修复"])')
w('        return SellDecision.hold()')
w('')

# === Confirm level ===
w('    def _check_confirm_level(self, close, high, low, open_, volume, df, state, today):')
w('        code = state.code if state.code else ""; sigs = []; ma10 = close.rolling(10).mean()')
w('        if self._signal_break_ma10(close, ma10): sigs.append("A2:破10日线")')
w('        if self._signal_high_long_shadow(high, close, open_): sigs.append("C1:高位长上影")')
w('        if self._signal_high_volume_negative(close, open_, volume): sigs.append("B3:高位放量阴")')
w('        if sigs: return SellDecision.reduce(code, CONFIRM_REDUCE_PCT, " | ".join(sigs), "确认层", sigs)')
w('        return SellDecision.hold()')
w('')

# === Clear level ===
w('    def _check_clear_level(self, close, high, low, volume, df, state, today):')
w('        code = state.code if state.code else ""')
w('        if not code: return SellDecision.hold()')
w('        ma20 = close.rolling(20).mean(); sigs = []')
w('        if self._signal_break_ma20_3days(close, ma20): sigs.append("A3:破20日线")')
w('        if self._signal_break_highest_low(close, high, low): sigs.append("C3:跌破起涨低点")')
w('        if len(sigs) >= 3:')
w('            return SellDecision.clear(code, "清仓信号过多: " + " | ".join(sigs), "清仓层", sigs)')
w('        if not (state.warning_reduced and not state.confirm_reduced):')
w('            if self._check_trailing_profit(close, high, low, state): sigs.append("移动止盈")')
w('        if sigs: return SellDecision.clear(code, " | ".join(sigs), "清仓层", sigs)')
w('        return SellDecision.hold()')
w('')

# === Trailing profit ===
w('    def _check_trailing_profit(self, close, high, low, state):')
w('        if state.cost_price <= 0 or state.highest_price <= 0: return False')
w('        p = float(close.iloc[-1])')
w('        profit = (p - state.cost_price) / state.cost_price')
w('        dd = (state.highest_price - p) / state.highest_price')
w('        if profit <= 0: return False')
w('        if profit < TRAILING_BREAK_MA5_INTERVAL:')
w('            return p < float(close.rolling(5).mean().iloc[-1])')
w('        if profit < 0.20: return dd >= TRAILING_DRAWDOWN_LO')
w('        if profit < 0.30: return dd >= TRAILING_DRAWDOWN_MID')
w('        if dd >= TRAILING_DRAWDOWN_HI: return True')
w('        if len(close) >= CHANDELIER_LOOKBACK:')
w('            atr = calc_atr(close, high, low, n=14)')
w('            lev = state.highest_price - CHANDELIER_ATR_MULTIPLE * float(atr.iloc[-1])')
w('            if p <= lev: return True')
w('        return False')
w('')

# === diagnose_position ===
w('    def diagnose_position(self, code, df, cost_price, current_price, highest_price):')
w('        state = self._states.get(code)')
w('        close = df["close"].astype(float)')
w('        high = df["high"].astype(float)')
w('        low = df["low"].astype(float)')
w('        open_ = df["open"].astype(float)')
w('        vol = df["volume"].astype(float)')
w('        profit_pct = (current_price - cost_price) / cost_price * 100 if cost_price > 0 else 0.0')
w('        if state is None:')
w('            status = "未跟踪"')
w('        elif state.cleared:')
w('            status = "已清仓(%s)" % state.cleared_date')
w('        elif state.confirm_reduced:')
w('            status = "确认已减仓"')
w('        elif state.warning_reduced:')
w('            status = "预警已减仓"')
w('        else:')
w('            status = "正常持有"')
w('        if state and state.cleared:')
w('            current_layer = "清仓层"')
w('        elif state and state.confirm_reduced:')
w('            current_layer = "确认层"')
w('        elif state and state.warning_reduced:')
w('            current_layer = "预警层"')
w('        else:')
w('            current_layer = "正常"')
w('        layers = {"bottom_line": {}, "warning": {}, "confirm": {}, "clear": {}, "trailing": {}}')
w('        if len(close) >= 2 and cost_price > 0:')
w('            curr = float(close.iloc[-1])')
w('            loss_pct = (curr - cost_price) / cost_price * 100')
w('            layers["bottom_line"]["累计亏损"] = {"triggered": loss_pct <= BOTTOM_LINE_LOSS_PCT * 100, "value": "%.1f%%" % loss_pct}')
w('            prev_close = float(close.iloc[-2])')
w('            if prev_close > 0:')
w('                daily_drop = (curr - prev_close) / prev_close * 100')
w('                layers["bottom_line"]["当日暴跌"] = {"triggered": daily_drop <= BOTTOM_LINE_DAILY_DROP_PCT * 100, "value": "%.1f%%" % daily_drop}')
w('        else:')
w('            layers["bottom_line"]["累计亏损"] = {"triggered": False, "value": "--"}')
w('            layers["bottom_line"]["当日暴跌"] = {"triggered": False, "value": "--"}')
w('        b1_t = False')
w('        b1_ratio = ""')
w('        if len(vol) >= 6 and len(close) >= 6:')
w('            v5 = vol.rolling(5).mean()')
w('            cv = float(vol.iloc[-1])')
w('            av = float(v5.iloc[-1])')
w('            if av > 0:')
w('                ratio = cv / av')
w('                if ratio >= VOLUME_RATIO_THRESHOLD:')
w('                    sh = detect_long_upper_shadow(high, close, open_)')
w('                    if sh.iloc[-1]:')
w('                        b1_t = True')
w('                b1_ratio = "%.1fx" % ratio')
w('        layers["warning"]["B1爆量"] = {"triggered": b1_t, "value": b1_ratio}')
w('        b2_t, b2_r = detect_volume_price_divergence(close, vol)')
w('        b2_val = "%.1fx" % b2_r if b2_r else ""')
w('        layers["warning"]["B2背离"] = {"triggered": b2_t, "value": b2_val}')
w('        c2_t = self._signal_macd_shortening(close)')
w('        layers["warning"]["C2绿缩"] = {"triggered": c2_t, "value": ""}')
w('        kdj_t = self._signal_kdj_death(close, high, low)')
w('        layers["warning"]["KDJ死叉"] = {"triggered": kdj_t, "value": ""}')
w('        ma10 = close.rolling(10).mean()')
w('        a2_t = self._signal_break_ma10(close, ma10)')
w('        a2_val = ""')
w('        if a2_t and len(close) >= 11:')
w('            a2_val = "%.1f%%" % ((float(ma10.iloc[-1]) - float(close.iloc[-1])) / float(ma10.iloc[-1]) * 100)')
w('        layers["confirm"]["A2破10"] = {"triggered": a2_t, "value": a2_val}')
w('        c1_t = self._signal_high_long_shadow(high, close, open_)')
w('        layers["confirm"]["C1上影"] = {"triggered": c1_t, "value": ""}')
w('        b3_t = self._signal_high_volume_negative(close, open_, vol)')
w('        layers["confirm"]["B3放量"] = {"triggered": b3_t, "value": ""}')
w('        ma20 = close.rolling(20).mean()')
w('        a3_t = self._signal_break_ma20_3days(close, ma20)')
w('        layers["clear"]["A3破20"] = {"triggered": a3_t, "value": ""}')
w('        c3_t = self._signal_break_highest_low(close, high, low)')
w('        layers["clear"]["C3破低"] = {"triggered": c3_t, "value": ""}')
w('        trailing_t = False')
w('        trailing_detail = ""')
w('        if cost_price > 0 and highest_price > 0:')
w('            profit_r = (current_price - cost_price) / cost_price')
w('            drawdown_pct = (highest_price - current_price) / highest_price * 100')
w('            ppv = profit_r * 100')
w('            if ppv > 0:')
w('                if ppv < TRAILING_BREAK_MA5_INTERVAL * 100:')
w('                    m5 = float(close.rolling(5).mean().iloc[-1]) if len(close) >= 5 else 0')
w('                    below = current_price < m5')
w('                    trailing_detail = "盈利%+.1f%%<%d%%, %s" % (ppv, int(TRAILING_BREAK_MA5_INTERVAL * 100), "跌破MA5" if below else "未破MA5")')
w('                    trailing_t = below')
w('                else:')
w('                    trailing_detail = "盈利%+.1f%%, 回撤%.1f%%" % (ppv, drawdown_pct)')
w('                    if ppv < 20:')
w('                        trailing_t = drawdown_pct >= TRAILING_DRAWDOWN_LO * 100')
w('                    elif ppv < 30:')
w('                        trailing_t = drawdown_pct >= TRAILING_DRAWDOWN_MID * 100')
w('                    else:')
w('                        trailing_t = drawdown_pct >= TRAILING_DRAWDOWN_HI * 100')
w('        layers["trailing"]["移动止盈"] = {"triggered": trailing_t, "detail": trailing_detail}')
w('        return {"code": code, "status": status, "cost_price": cost_price,')
w('                "current_price": current_price, "profit_pct": profit_pct,')
w('                "highest_price": highest_price, "current_layer": current_layer,')
w('                "layers": layers}')
w('')

# === Signal methods - correct signatures ===
w('    def _signal_break_ma5(self, close):')
w('        if len(close) < 6: return False')
w('        return bool(close.iloc[-1] < close.rolling(5).mean().iloc[-1])')
w('')
w('    def _signal_break_ma10(self, close, ma10):')
w('        if len(close) < 11: return False')
w('        return bool(close.iloc[-1] < ma10.iloc[-1])')
w('')
w('    def _signal_break_ma20_3days(self, close, ma20):')
w('        if len(close) < 24: return False')
w('        if close.iloc[-1] >= ma20.iloc[-1]: return False')
w('        n = 0')
w('        for i in range(min(CLEAR_MA20_DAYS, len(close)-1)):')
w('            if close.iloc[-1-i] < ma20.iloc[-1-i]: n += 1')
w('            else: break')
w('        return n >= CLEAR_MA20_DAYS')
w('')
w('    def _signal_explosive_volume(self, close, high, open_, vol):')
w('        if len(vol) < 6: return False, ""')
w('        v5 = vol.rolling(5).mean(); cv = float(vol.iloc[-1]); av = float(v5.iloc[-1])')
w('        if av <= 0 or cv/av < VOLUME_RATIO_THRESHOLD: return False, ""')
w('        sh = detect_long_upper_shadow(high, close, open_)')
w('        if not sh.iloc[-1]: return False, ""')
w('        return True, "B1:爆量上影(%.1f倍)" % (cv/av)')
w('')
w('    def _signal_b1_nextday_unrecovered(self, close, open_, state):')
w('        if len(close) < 2: return False')
w('        p = float(close.iloc[-1]); m5 = float(close.rolling(5).mean().iloc[-1])')
w('        if p > m5 and p > float(open_.iloc[-1]):')
w('            state.b1_needs_nextday_check = False; state.b1_additional_reduced = False; return False')
w('        return True')
w('')
w('    def _signal_volume_divergence(self, close, vol):')
w('        r, _ = detect_volume_price_divergence(close, vol); return r')
w('')
w('    def _signal_macd_shortening(self, close):')
w('        if len(close) < MACD_SHORTEN_DAYS + 26: return False')
w('        _, _, bar = self._calc_macd_safe(close)')
w('        if bar is None or len(bar) < MACD_SHORTEN_DAYS + 1: return False')
w('        for i in range(MACD_SHORTEN_DAYS + 1):')
w('            if pd.isna(bar.iloc[-1-i]): return False')
w('        if bar.iloc[-1] <= 0: return False')
w('        for i in range(MACD_SHORTEN_DAYS):')
w('            if bar.iloc[-1-i] >= bar.iloc[-2-i]: return False')
w('        return True')
w('')
w('    def _signal_kdj_death(self, close, high, low):')
w('        if len(close) < 15: return False')
w('        m5 = close.rolling(5).mean()')
w('        if len(m5) < 3: return False')
w('        a = calc_angle_simple(m5)')
w('        if a is None or abs(a) > MA5_SLOPE_FLAT_DEG: return False')
w('        k, d, j = calc_kdj(close, high, low)')
w('        if len(k) < 3 or len(d) < 3: return False')
w('        if pd.isna(k.iloc[-1]) or pd.isna(d.iloc[-1]) or pd.isna(k.iloc[-2]) or pd.isna(d.iloc[-2]): return False')
w('        return bool(k.iloc[-1] < d.iloc[-1] and k.iloc[-2] >= d.iloc[-2])')
w('')
w('    def _signal_high_long_shadow(self, high, close, open_):')
w('        if len(close) < 10: return False')
w('        rh = float(close.iloc[-5:].max()); cp = float(close.iloc[-10])')
w('        if cp <= 0 or (rh-cp)/cp < 0.05: return False')
w('        return bool(detect_long_upper_shadow(high, close, open_).iloc[-1])')
w('')
w('    def _signal_high_volume_negative(self, close, open_, vol):')
w('        if len(close) < 10: return False')
w('        if len(close) >= 20:')
w('            if float(close.iloc[-5:].max()) < float(close.iloc[-20:].max()) * 0.95: return False')
w('        if close.iloc[-1] >= open_.iloc[-1]: return False')
w('        if len(vol) >= 6:')
w('            if float(vol.iloc[-1]) < float(vol.rolling(5).mean().iloc[-1]) * VOLUME_RATIO_THRESHOLD: return False')
w('        return True')
w('')
w('    def _signal_break_highest_low(self, close, high, low):')
w('        if len(high) < 30: return False')
w('        r = high.iloc[-30:]; hv = r.max(); hp = 0')
w('        for i in range(len(r)):')
w('            if r.iloc[i] >= hv: hp = i; break')
w('        return float(close.iloc[-1]) < float(low.iloc[-30:].iloc[hp])')
w('')
w('    def _calc_macd_safe(self, close):')
w('        if len(close) < 26: return None, None, None')
w('        try:')
w('            e12 = close.ewm(span=12, adjust=False).mean()')
w('            e26 = close.ewm(span=26, adjust=False).mean()')
w('            d = e12 - e26; de = d.ewm(span=9, adjust=False).mean()')
w('            return d, de, 2*(d-de)')
w('        except Exception: return None, None, None')
w('')

# === Global variables ===
w('# ============================================================')
w('#  Global state')
w('# ============================================================')
w('_g_strategy_name = "risk_only"')
w('_g_account_id = ""')
w('_g_state_file = "state/sell_engine_state.json"')
w('_g_sell_engine = None')
w('_g_last_date = ""')
w('_g_pending_sells = {}')
w('_g_risk_log_entries = []')
w('_g_risk_log_written = False')
w('')

# === _reset_risk_log ===
w('def _reset_risk_log():')
w('    global _g_risk_log_entries, _g_risk_log_written')
w('    _g_risk_log_entries = []')
w('    _g_risk_log_written = False')
w('')

# === _append_risk_log ===
w('def _append_risk_log(timestamp, message):')
w('    global _g_risk_log_entries')
w('    if not timestamp:')
w('        timestamp = datetime.now().strftime("%H:%M:%S")')
w('    _g_risk_log_entries.append((timestamp, message))')
w('')

# === _get_ask1_price (QMT bridge) ===
w('def _get_ask1_price(C, code):')
w('    try:')
w('        tick = C.get_full_tick([code])')
w('        if tick and code in tick:')
w('            p = tick[code].get("askPrice1", 0)')
w('            if p and p > 0: return float(p)')
w('            p = tick[code].get("askPrice", 0)')
w('            if p and p > 0: return float(p)')
w('            p = tick[code].get("lastPrice", 0)')
w('            if p and p > 0: return float(p)')
w('        return 0.0')
w('    except Exception as e:')
w('        print("  [风控] %s 获取卖一价失败: %s" % (code, e))')
w('        return 0.0')
w('')

# === _sell_with_limit (QMT bridge) ===
w('def _sell_with_limit(C, code, shares, remark):')
w('    vol = int(shares)')
w('    if vol <= 0: return None')
w('    sell_price = _get_ask1_price(C, code)')
w('    if not sell_price or sell_price <= 0:')
w('        print("  [风控] %s 卖一价无效,跳过卖出" % code)')
w('        return None')
w('    try:')
w('        # passorder: 24=限价委托, 1101=卖出')
w('        fix_remark = "%s|%s" % (_g_strategy_name, remark)')
w('        # C.passorder(24, 1101, _g_account_id, code, fix_remark, sell_price, vol, \'\', 2)')
w('        # 使用C的卖出口')
w('        from xtquant.xttrader import XtOrderID')
w('        oid = C.order_place(_g_account_id, code, 24, 1101, sell_price, vol, "risk_order")')
w('        if oid and oid != -1:')
w('            print("  [风控] %s 委托卖出 %d股 价格=%.2f 原因=%s 委托号=%s" % (code, vol, sell_price, remark, str(oid)))')
w('            return oid')
w('        else:')
w('            print("  [风控] %s 委托失败: 返回%s" % (code, str(oid)))')
w('            return None')
w('    except Exception as e:')
w('        print("  [风控] %s 卖出异常: %s" % (code, e))')
w('        return None')
w('')

# === _retry_pending_sell ===
w('def _retry_pending_sell(code, info, C):')
w('    global _g_pending_sells')
w('    new_price = _get_ask1_price(C, code)')
w('    if not new_price or new_price <= 0:')
w('        print("    -> %s 获取价格失败,暂时跳过" % code)')
w('        return None')
w('    try:')
w('        oid = _sell_with_limit(C, code, info["volume"], "重试")')
w('        if oid:')
w('            info["retries"] += 1')
w('            info["order_id"] = oid')
w('            info["checks"] = 0')
w('            _g_pending_sells[code] = info')
w('            print("    -> %s 重试成功 新委托=%s" % (code, str(oid)))')
w('            return oid')
w('        else:')
w('            info["retries"] += 1')
w('            _g_pending_sells[code] = info')
w('            return None')
w('    except Exception as e:')
w('        print("    -> %s 重试异常: %s" % (code, e))')
w('        return None')
w('')

# === _check_pending_sells ===
w('def _check_pending_sells(C, today):')
w('    global _g_pending_sells')
w('    if not _g_pending_sells: return')
w('    try:')
w('        orders = get_trade_detail_data(_g_account_id, "STOCK", "order")')
w('    except Exception as e:')
w('        print("  [风控] 获取委托列表失败: %s" % e)')
w('        return')
w('    to_remove = []')
w('    for code, info in list(_g_pending_sells.items()):')
w('        oid = info.get("order_id", "")')
w('        vol = info.get("volume", 0)')
w('        retries = info.get("retries", 0)')
w('        checks = info.get("checks", 0)')
w('        if retries >= 3:')
w('            print("  [风控] %s 重试已达上限,放弃" % code)')
w('            to_remove.append(code)')
w('            continue')
w('        if checks >= 10:')
w('            print("  [风控] %s 检查已达上限,触发重试" % code)')
w('            info["checks"] = 0')
w('            _retry_pending_sell(code, info, C)')
w('            continue')
w('        found = False')
w('        for o in orders:')
w('            try:')
w('                order_id = getattr(o, "order_id", "") or getattr(o, "m_nOrderID", "")')
w('                if str(order_id) == str(oid):')
w('                    order_status = getattr(o, "order_status", -1) or getattr(o, "m_nOrderStatus", -1)')
w('                    deal_vol = getattr(o, "deal_vol", 0) or getattr(o, "m_nVolumeTraded", 0)')
w('                    if order_status in (5, 6, 7) or deal_vol >= vol:')
w('                        print("  [风控] %s 委托%s已成交(%d/%d)" % (code, oid, deal_vol, vol))')
w('                        found = True')
w('                        to_remove.append(code)')
w('                    else:')
w('                        found = True')
w('                        info["checks"] = checks + 1')
w('                        _g_pending_sells[code] = info')
w('                    break')
w('            except Exception:')
w('                continue')
w('        if not found:')
w('            info["checks"] = checks + 1')
w('            _g_pending_sells[code] = info')
w('    for c in to_remove:')
w('        _g_pending_sells.pop(c, None)')
w('')

# === _print_holdings_report (Formatting change #1 - qmt_wrapper format) ===
w('def _print_holdings_report(today, codes, pd, diagnosis_list):')
w('    """持仓报告：盘前持仓+账户持仓+对比表 (匹配qmt_wrapper格式)"""')
w('    tracked_codes = list(_g_sell_engine._states.keys()) if _g_sell_engine and _g_sell_engine._states else []')
w('    print()')
w('    print("=" * 55)')
w('    print("  持仓收盘报告 %s" % today)')
w('    print("=" * 55)')
w('    print()')
w('    print("  【盘前持仓】%d 只" % len(tracked_codes))')
w('    if tracked_codes:')
w('        for idx, c in enumerate(sorted(tracked_codes), 1):')
w('            state = _g_sell_engine._states.get(c) if _g_sell_engine else None')
w('            reason = get_trade_state_reason(state)')
w('            print("  %d. %s  %s" % (idx, c, reason))')
w('    else:')
w('        print("  (空)")')
w('    print()')
w('    print("  【账户持仓】%d 只" % len(codes))')
w('    if codes:')
w('        diag_map = {}')
w('        for d in diagnosis_list:')
w('            diag_map[d["code"]] = d')
w('        for idx, c in enumerate(sorted(codes), 1):')
w('            p = pd.get(c, {})')
w('            vol = p.get("volume", 0)')
w('            cost = p.get("cost", 0)')
w('            diag = diag_map.get(c, {})')
w('            curr = diag.get("current_price", 0) or cost')
w('            profit = diag.get("profit_pct", 0)')
w('            in_strategy = "★策略" if c in tracked_codes else "其他"')
w('            print("  %d. %s  %d股  成本=%.2f  现价=%.2f  盈亏=%+.1f%%  %s" % (idx, c, vol, cost, curr, profit, in_strategy))')
w('    else:')
w('        print("  (空)")')
w('    print()')
w('    print("  策略跟踪: %d 只 | 账户持有: %d 只" % (len(tracked_codes), len(codes)))')
w('    print("=" * 55)')
w('')

# === _format_plan_b_diagnosis ===
w('def _format_plan_b_diagnosis(diagnosis_list, today_str, now_str):')
w('    """将 diagnose_position() 返回的诊断列表格式化为风控诊断文本。"""')
w('    lines = []')
w('    lines.append("=" * 70)')
w('    lines.append("[风控专岗] 持仓风控明细 - %s %s" % (today_str, now_str))')
w('    lines.append("")')
w('    cnt_normal = 0; cnt_warning = 0; cnt_confirm = 0; cnt_clear = 0')
w('    for diag in diagnosis_list:')
w('        code = diag["code"]; status = diag["status"]')
w('        cost = diag["cost_price"]; curr = diag["current_price"]')
w('        profit = diag["profit_pct"]; highest = diag["highest_price"]')
w('        layer = diag["current_layer"]')
w('        if layer == "正常": cnt_normal += 1')
w('        elif layer == "预警层": cnt_warning += 1')
w('        elif layer == "确认层": cnt_confirm += 1')
w('        elif layer == "清仓层": cnt_clear += 1')
w('        lines.append(" %s ( %s . 成本%.2f . 现价%.2f . 盈利%+.1f%% . 最高%.2f )" % (code, status, cost, curr, profit, highest))')
w('        lines.append(" " + "-" * 65)')
w('        layers = diag["layers"]')
w('        def _sym(t): return "√" if t else "×"')
w('        bl_parts = []')
w('        for name, info in layers["bottom_line"].items():')
w('            if info.get("value") and info["value"] != "--":')
w('                bl_parts.append("%s: %s(%s)" % (name, _sym(info["triggered"]), info["value"]))')
w('            else:')
w('                bl_parts.append("%s: %s" % (name, _sym(info["triggered"])))')
w('        if bl_parts: lines.append(" 底线层   " + " | ".join(bl_parts))')
w('        w_names = list(layers["warning"].keys())')
w('        w_parts1 = []; w_parts2 = []')
w('        for name in w_names:')
w('            info = layers["warning"][name]')
w('            if info.get("value"):')
w('                s = "%s: %s(%s)" % (name, _sym(info["triggered"]), info["value"])')
w('            else:')
w('                s = "%s: %s" % (name, _sym(info["triggered"]))')
w('            if len(w_parts1) < 2: w_parts1.append(s)')
w('            else: w_parts2.append(s)')
w('        if w_parts1: lines.append(" 预警层   " + " | ".join(w_parts1))')
w('        if w_parts2: lines.append("          " + " | ".join(w_parts2))')
w('        c_parts = []')
w('        for name, info in layers["confirm"].items():')
w('            if info.get("value"):')
w('                c_parts.append("%s: %s(%s)" % (name, _sym(info["triggered"]), info["value"]))')
w('            else:')
w('                c_parts.append("%s: %s" % (name, _sym(info["triggered"])))')
w('        if c_parts: lines.append(" 确认层   " + " | ".join(c_parts))')
w('        cl_parts = []')
w('        for name, info in layers["clear"].items():')
w('            if info.get("value"):')
w('                cl_parts.append("%s: %s(%s)" % (name, _sym(info["triggered"]), info["value"]))')
w('            else:')
w('                cl_parts.append("%s: %s" % (name, _sym(info["triggered"])))')
w('        if cl_parts: lines.append(" 清仓层   " + " | ".join(cl_parts))')
w('        t_info = layers["trailing"]["移动止盈"]')
w('        if t_info.get("detail"):')
w('            lines.append(" 移动止盈  %s  %s" % (_sym(t_info["triggered"]), t_info["detail"]))')
w('        else:')
w('            lines.append(" 移动止盈  %s" % _sym(t_info["triggered"]))')
w('    lines.append("=" * 70)')
w('    total = len(diagnosis_list)')
w('    lines.append(" 汇总: 持仓%d只 | 持有中%d | 预警%d | 确认%d | 清仓%d" % (total, cnt_normal, cnt_warning, cnt_confirm, cnt_clear))')
w('    return lines')
w('')

# === _write_risk_log ===
w('def _write_risk_log(today, codes, pd, hd, dt, diagnosis_list, decisions):')
w('    global _g_risk_log_written, _g_risk_log_entries')
w('    if _g_risk_log_written: return')
w('    _g_risk_log_written = True')
w('    weekday_names = ["星期一","星期二","星期三","星期四","星期五","星期六","星期日"]')
w('    try:')
w('        d = datetime.strptime(today, "%Y%m%d")')
w('        date_str = d.strftime("%Y-%m-%d")')
w('        wd = weekday_names[d.weekday()]')
w('    except:')
w('        date_str = today; wd = ""')
w('    time_str = dt.strftime("%H:%M:%S") if hasattr(dt, "strftime") else str(dt)')
w('    lines = []')
w('    lines.append("=" * 66)')
w('    lines.append("  风险日志 - %s %s %s" % (date_str, wd, time_str))')
w('    lines.append("  策略=%s | 账户=%s" % (_g_strategy_name, _g_account_id))')
w('    lines.append("=" * 66)')
w('    lines.append("")')
w('    lines.append("  【账户持仓】%d 只" % len(codes))')
w('    for idx, c in enumerate(sorted(codes), 1):')
w('        p = pd.get(c, {})')
w('        vol = p.get("volume", 0); can_use = p.get("can_use", 0)')
w('        cost = p.get("cost", 0)')
w('        lines.append("  %d. %s  %d股(可用%d) 成本=%.2f" % (idx, c, vol, can_use, cost))')
w('    lines.append("")')
w('    lines.append("  【卖出决策】%d 条" % len(decisions))')
w('    for code, decision, shares in decisions:')
w('        signal_str = "|".join(decision.triggered_signals) if decision.triggered_signals else ""')
w('        lines.append("  %s  %s  %d股  层=%s  原因=%s  信号=%s" % (code, decision.action.value, shares, decision.triggered_layer, decision.reason, signal_str))')
w('    lines.append("")')
w('    lines.append("  【风控诊断】")')
w('    for line in _format_plan_b_diagnosis(diagnosis_list, today, time_str):')
w('        lines.append("  " + line)')
w('    lines.append("")')
w('    lines.append("  【日志明细】")')
w('    for ts, msg in _g_risk_log_entries:')
w('        lines.append("  [%s] %s" % (ts, msg))')
w('    lines.append("")')
w('    lines.append("=" * 66)')
w('    log_text = "\\n".join(lines)')
w('    try:')
w('        log_dir = "logs"')
w('        if not os.path.exists(log_dir): os.makedirs(log_dir)')
w('        log_path = os.path.join(log_dir, "risk_%s.log" % today)')
w('        with open(log_path, "a", encoding="utf-8") as f:')
w('            f.write(log_text + "\\n\\n")')
w('        print("  [风控] 日志已写入 %s" % log_path)')
w('    except Exception as e:')
w('        print("  [风控] 写入日志失败: %s" % e)')
w('')

# === init (entry point) ===
w('def init(C):')
w('    global _g_sell_engine')
w('    _g_sell_engine = SellStrategyEngine(')
w('        strategy_name=_g_strategy_name,')
w('        account_id=_g_account_id,')
w('        state_file=_g_state_file,')
w('        is_intraday=True,')
w('        hard_stop_loss=BOTTOM_LINE_LOSS_PCT,')
w('    )')
w('    _g_sell_engine.load_state()')
w('    C.sell_engine = _g_sell_engine')
w('    print("[风控专岗] 初始化完成，开始监控账户全持仓")')
w('')

# === handlebar (main bar handler with enhanced sell logs - Formatting changes #2 & #3) ===
w('def handlebar(C):')
w('    global _g_sell_engine, _g_last_date, _g_pending_sells, _g_risk_log_entries')
w('    if _g_sell_engine is None: return')
w('    try:')
w('        dt = C.get_current_time()')
w('    except:')
w('        dt = datetime.now()')
w('    try:')
w('        positions = get_trade_detail_data(_g_account_id, "STOCK", "position")')
w('    except Exception as e:')
w('        print("[风控] 获取持仓失败: %s" % e)')
w('        return')
w('    today = dt.strftime("%Y%m%d")')
w('    if today != _g_last_date:')
w('        _reset_risk_log()')
w('        _g_pending_sells = {}')
w('        _g_last_date = today')
w('        print("[风控] %s 风控检查开始" % today)')
w('    _append_risk_log("", "风控检查开始")')
w('    codes = set()')
w('    pd = {}')
w('    hd = {}')
w('    for pos in positions:')
w('        try:')
w('            code = getattr(pos, "m_strInstrumentID", "") or getattr(pos, "stock_code", "")')
w('            vol = getattr(pos, "m_nVolume", 0) or getattr(pos, "volume", 0)')
w('            can_use = getattr(pos, "m_nCanUse", 0) or getattr(pos, "can_use", 0)')
w('            cost = getattr(pos, "m_dOpenPrice", 0) or getattr(pos, "cost", 0)')
w('            if not code or vol <= 0: continue')
w('            codes.add(code)')
w('            pd[code] = {"volume": vol, "can_use": can_use, "cost": cost}')
w('            hd[code] = cost')
w('        except:')
w('            continue')
w('    if not codes:')
w('        _check_pending_sells(C, today)')
w('        _g_sell_engine.save_state()')
w('        return')
w('    try:')
w('        all_data = C.get_market_data_ex(stock_code=list(codes), period="1d", count=100)')
w('    except Exception as e:')
w('        print("[风控] 获取行情失败: %s" % e)')
w('        return')
w('    if not all_data: return')
w('    for code in list(all_data.keys()):')
w('        df = all_data[code]')
w('        if df is None or len(df) < 30:')
w('            all_data.pop(code, None)')
w('    try:')
w('        decisions = _g_sell_engine.evaluate(today, hd, all_data, pd)')
w('    except Exception as e:')
w('        print("[风控] 评估异常: %s" % e)')
w('        import traceback; traceback.print_exc()')
w('        return')
w('')
w('    # Enhanced sell log with 现价/盈亏/层/信号 (Formatting changes #2 & #3)')
w('    for code, decision, shares in decisions:')
w('        if shares < 100: continue')
w('        cost_price = pd.get(code, {}).get("cost", 0)')
w('        current_price = 0.0')
w('        if code in all_data:')
w('            df = all_data[code]')
w('            current_price = float(df["close"].astype(float).iloc[-1])')
w('        pnl_str = "%+.1f%%" % ((current_price - cost_price) / cost_price * 100) if cost_price > 0 else "--"')
w('        signal_str = "|".join(decision.triggered_signals) if decision.triggered_signals else ""')
w('        oid = _sell_with_limit(C, code, shares, decision.reason)')
w('        if oid:')
w('            _g_pending_sells[code] = {')
w('                "order_id": oid,')
w('                "volume": shares,')
w('                "retries": 0,')
w('                "checks": 0,')
w('            }')
w('            print("  [风控] %s  现价=%.2f  盈亏=%s  卖出%d股  原因=%s  层=%s  委托=%s" % (code, current_price, pnl_str, shares, decision.reason, decision.triggered_layer, oid))')
w('            _append_risk_log("sell_order: %s price=%.2f pnl=%s %dshares reason=%s layer=%s signals=%s oid=%s" % (code, current_price, pnl_str, shares, decision.reason, decision.triggered_layer, signal_str, oid))')
w('        else:')
w('            print("  [风控] %s  现价=%.2f  盈亏=%s  卖出%d股  原因=%s  层=%s  失败" % (code, current_price, pnl_str, shares, decision.reason, decision.triggered_layer))')
w('            _append_risk_log("sell_failed: %s price=%.2f pnl=%s %dshares reason=%s layer=%s signals=%s" % (code, current_price, pnl_str, shares, decision.reason, decision.triggered_layer, signal_str))')
w('')
w('    _check_pending_sells(C, today)')
w('')
w('    # Generate diagnosis list')
w('    diagnosis_list = []')
w('    for code in sorted(codes):')
w('        df = all_data.get(code)')
w('        if df is None: continue')
w('        p = pd.get(code, {})')
w('        cost = p.get("cost", 0)')
w('        curr = float(df["close"].astype(float).iloc[-1])')
w('        highest = _g_sell_engine._states.get(code, SellPositionState()).highest_price or curr')
w('        try:')
w('            diag = _g_sell_engine.diagnose_position(code, df, cost, curr, highest)')
w('            diagnosis_list.append(diag)')
w('        except Exception as e:')
w('            print("[风控] %s 诊断异常: %s" % (code, e))')
w('            continue')
w('')
w('    # Print holdings report (Formatting change #1)')
w('    _print_holdings_report(today, codes, pd, diagnosis_list)')
w('')
w('    tv = sum(p.get("volume", 0) for p in pd.values())')
w('    tc = sum(p.get("cost", 0) * p.get("volume", 0) for p in pd.values())')
w('    print("  [风控] 总计 %d 只持仓  股数=%d  总成本=%.2f" % (len(codes), tv, tc))')
w('')
w('    _write_risk_log(today, codes, pd, hd, dt, diagnosis_list, decisions)')
w('')

# === exit (cleanup) ===
w('def exit(C):')
w('    global _g_pending_sells, _g_sell_engine')
w('    if _g_pending_sells:')
w('        print("[风控专岗] 退出时仍有 %d 笔未成交委托" % len(_g_pending_sells))')
w('    if _g_sell_engine is not None:')
w('        _g_sell_engine.save_state()')
w('        print("[风控专岗] 状态已保存 %s" % _g_sell_engine.state_file)')
w('')

# ============ Write output ============
output = '\n'.join(out)

# Write in UTF-8 first (for development), then convert to GBK
output_path = 'risk_only_strategy.py'
with open(output_path, 'w', encoding='utf-8') as f:
    f.write(output)

# Verify
print('Written %d lines to %s' % (len(out), output_path))

# Check GBK compatibility
try:
    gbk_data = output.encode('gbk')
    print('GBK encoding: OK (%d bytes)' % len(gbk_data))
except Exception as e:
    print('GBK encoding FAILED: %s' % e)
    # Find the problematic character
    for i, ch in enumerate(output):
        try:
            ch.encode('gbk')
        except:
            print('  Problem char at pos %d: %r (U+%04X)' % (i, ch, ord(ch)))
            break
    sys.exit(1)

# Verify key elements
with open(output_path, 'r', encoding='utf-8') as f:
    content = f.read()

# Check for QMT 3.6.8 compatibility issues
issues = []
for i, line in enumerate(content.split('\n'), 1):
    if 'f"' in line or line.strip().startswith('f"'):
        issues.append('Line %d: f-string detected' % i)
    if 'f\'' in line or line.strip().startswith('f\''):
        issues.append('Line %d: f-string detected' % i)

if issues:
    print('QMT 3.6.8 compatibility issues:')
    for iss in issues:
        print('  - %s' % iss)
else:
    print('QMT 3.6.8 compatibility: OK (no f-strings)')

print('  Lines: %d' % len(out))
print('  File: %s' % output_path)
print('DONE')
